[project]
name = "inee-evaluaciones"
version = "0.1.0"
description = "Resultados de las evaluaciones del aprendizaje realizadas por el INEE del 2015 al 2018."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.5.0",
    "polars>=1.36.1",
    "streamlit>=1.52.2",
]
